name: Build Android APK

on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    branches-ignore:
      - gh-pages

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: web/package-lock.json
        
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install web dependencies
      run: |
        cd web
        npm ci
        
    - name: Build web application
      run: |
        cd web
        npm run build
        
    - name: Sync Capacitor
      run: |
        cd web
        npx cap sync android --no-build
        
    - name: Grant execute permission for gradlew
      run: chmod +x web/android/gradlew
      
    - name: Build debug APK
      run: |
        cd web/android
        ./gradlew assembleDebug
        
    - name: Upload debug APK
      uses: actions/upload-artifact@v4
      with:
        name: pqtorus-debug-${{ github.sha }}
        path: web/android/app/build/outputs/apk/debug/app-debug.apk
        
    - name: Build release APK
      run: |
        cd web/android
        ./gradlew assembleRelease
        
    - name: Upload release APK
      uses: actions/upload-artifact@v4
      with:
        name: pqtorus-release-${{ github.sha }}
        path: web/android/app/build/outputs/apk/release/app-release-unsigned.apk